# Generated by Django 4.1.5 on 2023-01-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Товар')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, max_length=100, null=True, verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
